### ISSUE TITLE
Where's the last version?

### ISSUE THREAD

**Issue by Freeaqingme** [solarissmoke/disable-feeds#1]
First of all, thank you for providing this plugin.

I noticed the the wordpress plugin site had a version 1.4.4, whereas this repo only goes up to 1.4.2. So I was wondering if there's a git repo available that also contains the latest changes?

Thanks!

**Comment by solarissmoke** [comment]
I think I'd forgotten to make changes here and just pushed directly to WP.org... have just snychronised both repos. Thanks!

**Comment by Freeaqingme** [comment]
That's quick! Tnx!
